/*amd /GridView/_General/visibleRowNum_visibleRowNumFix_GridView/visibleRowNum_visibleRowNumFix_GridView.xml 3794 d0cf60005aca782b6f2e0c0052239508e6991392e397bbe5814feb223bdb01e3 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'DEFAULT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{baseNode:'list',id:'dataList1',repeatNode:'map',saveRemovedData:'true',style:''},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{dataType:'text',id:'Depth',name:'Depth'}},{T:1,N:'w2:column',A:{dataType:'text',id:'Region',name:'Region'}},{T:1,N:'w2:column',A:{dataType:'text',id:'Population',name:'Population',valueType:''}},{T:1,N:'w2:column',A:{dataType:'text',id:'Area',name:'Area'}},{T:1,N:'w2:column',A:{dataType:'text',id:'GDP',name:'GDP'}},{T:1,N:'w2:column',A:{dataType:'text',id:'Literacy',name:'Literacy'}},{T:1,N:'w2:column',A:{dataType:'text',id:'Phones',name:'Phones'}},{T:1,N:'w2:column',A:{dataType:'text',id:'Birthrate',name:'Birthrate'}},{T:1,N:'w2:column',A:{dataType:'text',id:'Deathrate',name:'Deathrate'}}]}]}]},{T:1,N:'w2:workflowCollection'},{T:1,N:'xf:submission',A:{id:'submission1',ref:'',target:'data:json,dataList1',action:'population.json',method:'post',mediatype:'application/json',encoding:'UTF-8',instance:'',replace:'',errorHandler:'',customHandler:'',mode:'asynchronous',processMsg:'','ev:submit':'','ev:submitdone':'','ev:submiterror':'',abortTrigger:''}}]},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
        
	scwin.onpageload = function() {
		$p.executeSubmission("submission1");
		
	};
	
	scwin.onpageunload = function() {
		
	};
	
	
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload','ev:onpageunload':'scwin.onpageunload'},E:[{T:1,N:'w2:textbox',A:{id:'',label:'visibleRowNumFix',style:'width:240px;text-align:center;line-height: 32px;height:32px;margin:20px;margin-bottom:30px;background-color:#C0C0C0;font-size:17px;font-family:monospace;font-style:normal;font-weight:bolder;'}},{T:1,N:'w2:gridView',A:{id:'',style:'width: 95%;margin: 20px;',scrollByColumn:'false',defaultCellHeight:'20',scrollByColumnAdaptive:'false',dataList:'data:dataList1',autoFit:'allColumn',rowNumVisible:'true',visibleRowNum:'20',visibleRowNumFix:'true',filterBoxvisibleRowNum:'0'},E:[{T:1,N:'w2:caption',A:{style:'',id:'caption1',value:'this is a grid caption.'}},{T:1,N:'w2:header',A:{style:'',id:'header1'},E:[{T:1,N:'w2:row',A:{style:'',id:'row1'},E:[{T:1,N:'w2:column',A:{width:'70',id:'column19',value:'Depth'}},{T:1,N:'w2:column',A:{width:'70',id:'column20',value:'Region'}},{T:1,N:'w2:column',A:{width:'70',id:'column21',value:'Population'}},{T:1,N:'w2:column',A:{width:'70',id:'column22',value:'Area'}},{T:1,N:'w2:column',A:{width:'70',id:'column23',value:'GDP'}},{T:1,N:'w2:column',A:{width:'70',id:'column24',value:'Literacy'}},{T:1,N:'w2:column',A:{width:'70',id:'column25',value:'Phones'}},{T:1,N:'w2:column',A:{width:'70',id:'column26',value:'Birthrate'}},{T:1,N:'w2:column',A:{width:'70',id:'column27',value:'Deathrate'}}]}]},{T:1,N:'w2:gBody',A:{style:'',id:'gBody1'},E:[{T:1,N:'w2:row',A:{style:'',id:'row2'},E:[{T:1,N:'w2:column',A:{width:'70',id:'Depth'}},{T:1,N:'w2:column',A:{width:'70',id:'Region',inputType:'drilldown',showDepth:'3',depthColumn:'Depth',depthType:'line',style:'text-align: left;'}},{T:1,N:'w2:column',A:{width:'70',id:'Population'}},{T:1,N:'w2:column',A:{width:'70',id:'Area'}},{T:1,N:'w2:column',A:{width:'70',id:'GDP'}},{T:1,N:'w2:column',A:{width:'70',id:'Literacy'}},{T:1,N:'w2:column',A:{width:'70',id:'Phones'}},{T:1,N:'w2:column',A:{width:'70',id:'Birthrate'}},{T:1,N:'w2:column',A:{width:'70',id:'Deathrate'}}]}]}]}]}]}]})