/*amd /InputBox/maxLength_InputBox.xml 3347 95d7c55e2c6ee23adee16009687fadd54782f7a254e5fa1edbc08f9b8a7336ec */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'DEFAULT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'}},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
        
	scwin.onpageload = function() {
		
	};
	
	scwin.onpageunload = function() {
		
	};
	
	
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload','ev:onpageunload':'scwin.onpageunload'},E:[{T:1,N:'xf:group',A:{tagname:'table',style:'width:60%;margin: 100px;margin-left: 200px;',id:'',class:'w2tb'},E:[{T:1,N:'w2:attributes',E:[{T:1,N:'w2:summary'}]},{T:1,N:'xf:group',A:{tagname:'caption'}},{T:1,N:'xf:group',A:{tagname:'colgroup'},E:[{T:1,N:'xf:group',A:{tagname:'col',style:'width:50.00%;'}},{T:1,N:'xf:group',A:{tagname:'col',style:'width:50.00%'}}]},{T:1,N:'xf:group',A:{tagname:'tr',style:''},E:[{T:1,N:'xf:group',A:{tagname:'th',class:'w2tb_th',style:'font-size:18px;font-family: monospace;'},E:[{T:3,text:'dataType="text"'},{T:1,N:'w2:attributes',E:[{T:1,N:'w2:scope',E:[{T:3,text:'row'}]}]}]},{T:1,N:'xf:group',A:{tagname:'td',class:'w2tb_td',style:'padding: 10px;'},E:[{T:1,N:'w2:attributes'},{T:1,N:'xf:input',A:{adjustMaxLength:'false',id:'',style:'width:85%;height:40px;padding: 10px;font-size:20px;font-family:monospace;font-style:normal;font-weight:bolder;',maxlength:''}}]}]},{T:1,N:'xf:group',A:{tagname:'tr',style:''},E:[{T:1,N:'xf:group',A:{tagname:'th',style:'font-size:18px;font-family: monospace;',class:'w2tb_th'},E:[{T:3,text:'dataType="euro"'},{T:1,N:'w2:attributes',E:[{T:1,N:'w2:scope',E:[{T:3,text:'row'}]}]}]},{T:1,N:'xf:group',A:{tagname:'td',style:'padding: 10px;',class:'w2tb_td'},E:[{T:1,N:'xf:input',A:{adjustMaxLength:'false',dataType:'euro',euroMask:'#.###,##',id:'input1',style:'width:85%;height:40px;padding: 10px;font-size:20px;font-family:monospace;font-style:normal;font-weight:bolder;',maxlength:'5'}}]}]},{T:1,N:'xf:group',A:{tagname:'tr',style:''},E:[{T:1,N:'xf:group',A:{tagname:'th',style:'font-size:18px;font-family: monospace;',class:'w2tb_th'},E:[{T:3,text:'dataType="rupee"'},{T:1,N:'w2:attributes',E:[{T:1,N:'w2:scope',E:[{T:3,text:'row'}]}]}]},{T:1,N:'xf:group',A:{tagname:'td',style:'padding: 10px;',class:'w2tb_td'},E:[{T:1,N:'xf:input',A:{adjustMaxLength:'false',dataType:'rupee',id:'input3',rupeeMask:'##,##,###.##',style:'width:85%;height:40px;padding: 10px;font-size:20px;font-family:monospace;font-style:normal;font-weight:bolder;',maxlength:'5'}}]}]},{T:1,N:'xf:group',A:{tagname:'tr',style:''},E:[{T:1,N:'xf:group',A:{tagname:'th',style:'font-size:18px;font-family: monospace;',class:'w2tb_th'},E:[{T:3,text:'dataType="tenge"'},{T:1,N:'w2:attributes',E:[{T:1,N:'w2:scope',E:[{T:3,text:'row'}]}]}]},{T:1,N:'xf:group',A:{tagname:'td',style:'padding: 10px;',class:'w2tb_td'},E:[{T:1,N:'xf:input',A:{adjustMaxLength:'false',dataType:'tenge',disabled:'',id:'input5',style:'width:85%;height:40px;padding: 10px;font-size:20px;font-family:monospace;font-style:normal;font-weight:bolder;',tengeMask:'# ###.00',maxlength:'5'}}]}]}]}]}]}]})