/*amd /Spinner/dateIncrementType_dataType_time_Spinner.xml 3575 0fce44a947939a86d17bd945992ceab55c89ba6f0fa85008cde633859155ad04 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'DEFAULT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataMap',A:{baseNode:'map',id:'dataMap1'},E:[{T:1,N:'w2:keyInfo',E:[{T:1,N:'w2:key',A:{id:'key1',name:'name1',dataType:'text'}},{T:1,N:'w2:key',A:{id:'key2',name:'name2',dataType:'text'}},{T:1,N:'w2:key',A:{id:'key3',name:'name3',dataType:'text'}}]}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
        
	scwin.onpageload = function() {
		dataMap1.setArray(["111233", "1112", "1100"]);        
	};
	
	scwin.onpageunload = function() {
		
	};
	
	
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload','ev:onpageunload':'scwin.onpageunload'},E:[{T:1,N:'w2:textbox',A:{id:'',label:'dataType"time"',style:'width:338px;padding: 10px;text-align:left;line-height:32px;height:32px;margin:50px;margin-bottom: 0px;margin-bottom:30px;background-color:#C0C0C0;font-size:17px;font-family:monospace;font-style:normal;font-weight:bolder;'}},{T:1,N:'xf:group',A:{tagname:'table',style:'width:60%;margin: 50px;',id:'',class:'w2tb'},E:[{T:1,N:'w2:attributes',E:[{T:1,N:'w2:summary'}]},{T:1,N:'xf:group',A:{tagname:'caption'}},{T:1,N:'xf:group',A:{tagname:'colgroup'},E:[{T:1,N:'xf:group',A:{tagname:'col',style:'width:50.00%;'}},{T:1,N:'xf:group',A:{tagname:'col',style:'width:50.00%'}}]},{T:1,N:'xf:group',A:{tagname:'tr',style:''},E:[{T:1,N:'xf:group',A:{tagname:'th',style:'font-size:15px;font-family:monospace;font-style:normal;font-weight:bolder;text-align: left;',class:'w2tb_th'},E:[{T:3,text:'dateIncrementType="second"'},{T:1,N:'w2:attributes',E:[{T:1,N:'w2:scope',E:[{T:3,text:'row'}]}]}]},{T:1,N:'xf:group',A:{tagname:'td',style:'',class:'w2tb_td'},E:[{T:1,N:'w2:spinner',A:{autoFocus:'',buttonSize:'30',dataType:'time',dateIncrementType:'second',id:'key1',inputReadOnly:'false',nextTabID:'',ref:'data:dataMap1.key1',skin:'type1',style:'position: relative;width: 150px;height: 21px;margin: 10px;'}}]}]},{T:1,N:'xf:group',A:{tagname:'tr',style:''},E:[{T:1,N:'xf:group',A:{tagname:'th',style:'font-size:15px;font-family:monospace;font-style:normal;font-weight:bolder;text-align: left;',class:'w2tb_th'},E:[{T:3,text:'dateIncrementType="minute"'},{T:1,N:'w2:attributes',E:[{T:1,N:'w2:scope',E:[{T:3,text:'row'}]}]}]},{T:1,N:'xf:group',A:{tagname:'td',style:'',class:'w2tb_td'},E:[{T:1,N:'w2:spinner',A:{autoFocus:'',buttonSize:'30',dataType:'time',dateIncrementType:'minute',id:'key2',inputReadOnly:'false',nextTabID:'',ref:'data:dataMap1.key2',skin:'type1',style:'position: relative;width: 150px;margin: 10px;height: 21px;'}}]}]},{T:1,N:'xf:group',A:{tagname:'tr',style:''},E:[{T:1,N:'xf:group',A:{tagname:'th',style:'font-size:15px;font-family:monospace;font-style:normal;font-weight:bolder;text-align: left;',class:'w2tb_th'},E:[{T:3,text:'dateIncrementType="hour"'},{T:1,N:'w2:attributes',E:[{T:1,N:'w2:scope',E:[{T:3,text:'row'}]}]}]},{T:1,N:'xf:group',A:{tagname:'td',style:'',class:'w2tb_td'},E:[{T:1,N:'w2:spinner',A:{autoFocus:'',buttonSize:'30',dataType:'time',dateIncrementType:'hour',id:'key3',inputReadOnly:'false',nextTabID:'',ref:'data:dataMap1.key3',skin:'type1',style:'position: relative;width: 150px;margin: 10px;height: 21px;'}}]}]}]}]}]}]})