/*amd /gridView-015/gridView_inputType_text_WPF_1271.xml 3003 570199bd8eba4d6937b131804285e1ef2061f381bbbbb454fe37c355cfd43460 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{id:'dataList1',baseNode:'list',saveRemovedData:'true',repeatNode:'map'},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{id:'col1',name:'name1',dataType:'text'}},{T:1,N:'w2:column',A:{id:'col2',name:'name2',dataType:'text'}},{T:1,N:'w2:column',A:{id:'col3',name:'name3',dataType:'text'}}]},{T:1,N:'w2:data',A:{use:'true'},E:[{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'1'}]},{T:1,N:'col2',E:[{T:4,cdata:'2'}]},{T:1,N:'col3',E:[{T:4,cdata:'3'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'4'}]},{T:1,N:'col2',E:[{T:4,cdata:'5'}]},{T:1,N:'col3',E:[{T:4,cdata:'6'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'7'}]},{T:1,N:'col2',E:[{T:4,cdata:'8'}]},{T:1,N:'col3',E:[{T:4,cdata:'9'}]}]}]}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
        
		scwin.onpageload = function() {
			
		};
		
		scwin.onpageunload = function() {
			
		};
		
}}}]}]},{T:1,N:'style',E:[{T:3,text:'\r\n    .w2grid_input {\r\n    	/* display:inline-block; */\r\n    	/* width:50px; */\r\n    	border:2px solid #b3b3b3;\r\n	}\r\n    '}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload','ev:onpageunload':'scwin.onpageunload'},E:[{T:1,N:'w2:gridView',A:{dataList:'dataList1',scrollByColumn:'false',id:'',style:'position: absolute;width: 500px;height: 150px;left:80px;top:97px;',ignoreCellClick:'false',ignoreToggleOnDisabled:'false',fixedColumnWithHidden:'true',useShiftKey:'true',readOnly:'false'},E:[{T:1,N:'w2:header',A:{id:'header1',style:''},E:[{T:1,N:'w2:row',A:{id:'row2',style:''},E:[{T:1,N:'w2:column',A:{blockSelect:'false',id:'column3',style:'height:20px',width:'70',inputType:'text',displayMode:'label',value:'name1'}},{T:1,N:'w2:column',A:{blockSelect:'false',id:'column5',style:'height:20px',inputType:'text',width:'70',displayMode:'label',value:'name2'}},{T:1,N:'w2:column',A:{blockSelect:'false',id:'column4',style:'height:20px',inputType:'text',width:'70',displayMode:'label',value:'name3'}}]}]},{T:1,N:'w2:gBody',A:{id:'gBody6',style:''},E:[{T:1,N:'w2:row',A:{id:'row7',style:''},E:[{T:1,N:'w2:column',A:{blockSelect:'false',id:'col1',style:'height:20px',width:'70',inputType:'text',displayMode:'label'}},{T:1,N:'w2:column',A:{blockSelect:'false',id:'col2',style:'height:20px',width:'70',inputType:'text',displayMode:'label',inputTypeTextClass:'w2text_input'}},{T:1,N:'w2:column',A:{blockSelect:'false',id:'col3',style:'height:20px',width:'70',inputType:'text',displayMode:'label'}}]}]}]}]}]}]})