/*amd /GridView/Events/oncellclick_GridView.xml 62509 39eceb5b0d1fa1ade7ac98f6416c160813426cfec100208d125caf2fac085834 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:7,N:'xml-stylesheet',instruction:'href="/2019-09/Components/gridview.css" type="text/css"'},{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'DEFAULT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{baseNode:'list',repeatNode:'map',id:'dataList1',saveRemovedData:'true'},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{id:'Check',name:'Check',dataType:'text'}},{T:1,N:'w2:column',A:{id:'ID',name:'ID',dataType:'text'}},{T:1,N:'w2:column',A:{id:'Age',name:'Age',dataType:'text'}},{T:1,N:'w2:column',A:{id:'Status',name:'Status',dataType:'text'}},{T:1,N:'w2:column',A:{id:'Income',name:'Income',dataType:'text'}},{T:1,N:'w2:column',A:{id:'Expense',name:'Expense',dataType:'text'}},{T:1,N:'w2:column',A:{id:'Hobby',name:'Hobby',dataType:'text'}},{T:1,N:'w2:column',A:{id:'Region',name:'Region',dataType:'text'}},{T:1,N:'w2:column',A:{id:'Frequency',name:'Frequency',dataType:'text'}},{T:1,N:'w2:column',A:{id:'date',name:'date',dataType:'text'}}]}]},{T:1,N:'w2:dataList',A:{baseNode:'list',repeatNode:'map',id:'dataList2',saveRemovedData:'true'},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{id:'label',name:'label',dataType:'text'}},{T:1,N:'w2:column',A:{id:'value',name:'value',dataType:'text'}},{T:1,N:'w2:column',A:{id:'col3',name:'name3',dataType:'text'}}]},{T:1,N:'w2:data',A:{use:'true'},E:[{T:1,N:'w2:row',E:[{T:1,N:'label',E:[{T:4,cdata:'Single'}]},{T:1,N:'value',E:[{T:4,cdata:'Single'}]},{T:1,N:'col3',E:[{T:4,cdata:'true'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'label',E:[{T:4,cdata:'Divorced'}]},{T:1,N:'value',E:[{T:4,cdata:'Divorced'}]},{T:1,N:'col3',E:[{T:4,cdata:'true'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'label',E:[{T:4,cdata:'Married'}]},{T:1,N:'value',E:[{T:4,cdata:'Married'}]},{T:1,N:'col3',E:[{T:4,cdata:'true'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'label',E:[{T:4,cdata:'None'}]},{T:1,N:'value',E:[{T:4,cdata:'None'}]},{T:1,N:'col3',E:[{T:4,cdata:'false'}]}]}]}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
        
	scwin.onpageload = function() {
		
		var json = [
    {
        "ID": "10001",
        "Age": "23",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/07/19",
        "rowStatus": "R"
    },
    {
        "ID": "10002",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "2,300,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/04/03",
        "rowStatus": "R"
    },
    {
        "ID": "10003",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10004",
        "Age": "19",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "1,900,000",
        "Frequency": "5",
        "Expense": "80,000",
        "Date": "2019/05/10",
        "rowStatus": "R"
    },
    {
        "ID": "10005",
        "Age": "34",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "3,500,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10006",
        "Age": "39",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "8",
        "Expense": "500,000",
        "Date": "2019/05/13",
        "rowStatus": "R"
    },
    {
        "ID": "10007",
        "Age": "29",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/04/30",
        "rowStatus": "R"
    },
    {
        "ID": "10008",
        "Age": "25",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "12",
        "Expense": "2,000,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10009",
        "Age": "32",
        "Region": "Incheon",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/04/15",
        "rowStatus": "R"
    },
    {
        "ID": "10010",
        "Age": "34",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,500,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10011",
        "Age": "36",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,000,000",
        "Frequency": "5",
        "Expense": "230,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10012",
        "Age": "22",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "2,000,000",
        "Frequency": "2",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10013",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "80,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10014",
        "Age": "40",
        "Region": "Jeju",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,500,000",
        "Frequency": "8",
        "Expense": "100,000",
        "Date": "2019/05/09",
        "rowStatus": "R"
    },
    {
        "ID": "10015",
        "Age": "35",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,100,000",
        "Frequency": "3",
        "Expense": "350,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10016",
        "Age": "31",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10017",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10018",
        "Age": "33",
        "Region": "Daegu",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10019",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10020",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "3,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10021",
        "Age": "37",
        "Region": "Busan",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10022",
        "Age": "28",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10023",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10024",
        "Age": "20",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,300,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10025",
        "Age": "19",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10026",
        "Age": "32",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "8",
        "Expense": "300,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10027",
        "Age": "34",
        "Region": "Busan",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10028",
        "Age": "41",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "1",
        "Expense": "30,000",
        "Date": "2019/04/18",
        "rowStatus": "R"
    },
    {
        "ID": "10029",
        "Age": "42",
        "Region": "Incheon",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "5",
        "Expense": "120,000",
        "Date": "2019/5/8",
        "rowStatus": "R"
    },
    {
        "ID": "10030",
        "Age": "39",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,800,000",
        "Frequency": "8",
        "Expense": "400,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10001",
        "Age": "23",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/07/19",
        "rowStatus": "R"
    },
    {
        "ID": "10002",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "2,300,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/04/03",
        "rowStatus": "R"
    },
    {
        "ID": "10003",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10004",
        "Age": "19",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "1,900,000",
        "Frequency": "5",
        "Expense": "80,000",
        "Date": "2019/05/10",
        "rowStatus": "R"
    },
    {
        "ID": "10005",
        "Age": "34",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "3,500,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10006",
        "Age": "39",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "8",
        "Expense": "500,000",
        "Date": "2019/05/13",
        "rowStatus": "R"
    },
    {
        "ID": "10007",
        "Age": "29",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/04/30",
        "rowStatus": "R"
    },
    {
        "ID": "10008",
        "Age": "25",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "12",
        "Expense": "2,000,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10009",
        "Age": "32",
        "Region": "Incheon",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/04/15",
        "rowStatus": "R"
    },
    {
        "ID": "10010",
        "Age": "34",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,500,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10011",
        "Age": "36",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,000,000",
        "Frequency": "5",
        "Expense": "230,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10012",
        "Age": "22",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "2,000,000",
        "Frequency": "2",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10013",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "80,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10014",
        "Age": "40",
        "Region": "Jeju",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,500,000",
        "Frequency": "8",
        "Expense": "100,000",
        "Date": "2019/05/09",
        "rowStatus": "R"
    },
    {
        "ID": "10015",
        "Age": "35",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,100,000",
        "Frequency": "3",
        "Expense": "350,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10016",
        "Age": "31",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10017",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10018",
        "Age": "33",
        "Region": "Daegu",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10019",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10020",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "3,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10021",
        "Age": "37",
        "Region": "Busan",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10022",
        "Age": "28",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10023",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10024",
        "Age": "20",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,300,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10025",
        "Age": "19",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10026",
        "Age": "32",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "8",
        "Expense": "300,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10027",
        "Age": "34",
        "Region": "Busan",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10028",
        "Age": "41",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "1",
        "Expense": "30,000",
        "Date": "2019/04/18",
        "rowStatus": "R"
    },
    {
        "ID": "10029",
        "Age": "42",
        "Region": "Incheon",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "5",
        "Expense": "120,000",
        "Date": "2019/5/8",
        "rowStatus": "R"
    },
    {
        "ID": "10030",
        "Age": "39",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,800,000",
        "Frequency": "8",
        "Expense": "400,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10001",
        "Age": "23",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/07/19",
        "rowStatus": "R"
    },
    {
        "ID": "10002",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "2,300,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/04/03",
        "rowStatus": "R"
    },
    {
        "ID": "10003",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10004",
        "Age": "19",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "1,900,000",
        "Frequency": "5",
        "Expense": "80,000",
        "Date": "2019/05/10",
        "rowStatus": "R"
    },
    {
        "ID": "10005",
        "Age": "34",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "3,500,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10006",
        "Age": "39",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "8",
        "Expense": "500,000",
        "Date": "2019/05/13",
        "rowStatus": "R"
    },
    {
        "ID": "10007",
        "Age": "29",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/04/30",
        "rowStatus": "R"
    },
    {
        "ID": "10008",
        "Age": "25",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "12",
        "Expense": "2,000,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10009",
        "Age": "32",
        "Region": "Incheon",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/04/15",
        "rowStatus": "R"
    },
    {
        "ID": "10010",
        "Age": "34",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,500,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10011",
        "Age": "36",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,000,000",
        "Frequency": "5",
        "Expense": "230,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10012",
        "Age": "22",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "2,000,000",
        "Frequency": "2",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10013",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "80,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10014",
        "Age": "40",
        "Region": "Jeju",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,500,000",
        "Frequency": "8",
        "Expense": "100,000",
        "Date": "2019/05/09",
        "rowStatus": "R"
    },
    {
        "ID": "10015",
        "Age": "35",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,100,000",
        "Frequency": "3",
        "Expense": "350,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10016",
        "Age": "31",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10017",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10018",
        "Age": "33",
        "Region": "Daegu",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10019",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10020",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "3,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10021",
        "Age": "37",
        "Region": "Busan",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10022",
        "Age": "28",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10023",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10024",
        "Age": "20",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,300,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10025",
        "Age": "19",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10026",
        "Age": "32",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "8",
        "Expense": "300,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10027",
        "Age": "34",
        "Region": "Busan",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10028",
        "Age": "41",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "1",
        "Expense": "30,000",
        "Date": "2019/04/18",
        "rowStatus": "R"
    },
    {
        "ID": "10029",
        "Age": "42",
        "Region": "Incheon",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "5",
        "Expense": "120,000",
        "Date": "2019/5/8",
        "rowStatus": "R"
    },
    {
        "ID": "10030",
        "Age": "39",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,800,000",
        "Frequency": "8",
        "Expense": "400,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10001",
        "Age": "23",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/07/19",
        "rowStatus": "R"
    },
    {
        "ID": "10002",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "2,300,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/04/03",
        "rowStatus": "R"
    },
    {
        "ID": "10003",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10004",
        "Age": "19",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "1,900,000",
        "Frequency": "5",
        "Expense": "80,000",
        "Date": "2019/05/10",
        "rowStatus": "R"
    },
    {
        "ID": "10005",
        "Age": "34",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "3,500,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10006",
        "Age": "39",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "8",
        "Expense": "500,000",
        "Date": "2019/05/13",
        "rowStatus": "R"
    },
    {
        "ID": "10007",
        "Age": "29",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/04/30",
        "rowStatus": "R"
    },
    {
        "ID": "10008",
        "Age": "25",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "12",
        "Expense": "2,000,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10009",
        "Age": "32",
        "Region": "Incheon",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/04/15",
        "rowStatus": "R"
    },
    {
        "ID": "10010",
        "Age": "34",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,500,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10011",
        "Age": "36",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,000,000",
        "Frequency": "5",
        "Expense": "230,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10012",
        "Age": "22",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "2,000,000",
        "Frequency": "2",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10013",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "80,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10014",
        "Age": "40",
        "Region": "Jeju",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,500,000",
        "Frequency": "8",
        "Expense": "100,000",
        "Date": "2019/05/09",
        "rowStatus": "R"
    },
    {
        "ID": "10015",
        "Age": "35",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,100,000",
        "Frequency": "3",
        "Expense": "350,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10016",
        "Age": "31",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10017",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10018",
        "Age": "33",
        "Region": "Daegu",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10019",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10020",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "3,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10021",
        "Age": "37",
        "Region": "Busan",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10022",
        "Age": "28",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10023",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10024",
        "Age": "20",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,300,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10025",
        "Age": "19",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10026",
        "Age": "32",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "8",
        "Expense": "300,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10027",
        "Age": "34",
        "Region": "Busan",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10028",
        "Age": "41",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "1",
        "Expense": "30,000",
        "Date": "2019/04/18",
        "rowStatus": "R"
    },
    {
        "ID": "10029",
        "Age": "42",
        "Region": "Incheon",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "5",
        "Expense": "120,000",
        "Date": "2019/5/8",
        "rowStatus": "R"
    },
    {
        "ID": "10030",
        "Age": "39",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,800,000",
        "Frequency": "8",
        "Expense": "400,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10001",
        "Age": "23",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/07/19",
        "rowStatus": "R"
    },
    {
        "ID": "10002",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "2,300,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/04/03",
        "rowStatus": "R"
    },
    {
        "ID": "10003",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10004",
        "Age": "19",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "1,900,000",
        "Frequency": "5",
        "Expense": "80,000",
        "Date": "2019/05/10",
        "rowStatus": "R"
    },
    {
        "ID": "10005",
        "Age": "34",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "3,500,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10006",
        "Age": "39",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "8",
        "Expense": "500,000",
        "Date": "2019/05/13",
        "rowStatus": "R"
    },
    {
        "ID": "10007",
        "Age": "29",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/04/30",
        "rowStatus": "R"
    },
    {
        "ID": "10008",
        "Age": "25",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "12",
        "Expense": "2,000,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10009",
        "Age": "32",
        "Region": "Incheon",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/04/15",
        "rowStatus": "R"
    },
    {
        "ID": "10010",
        "Age": "34",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,500,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10011",
        "Age": "36",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,000,000",
        "Frequency": "5",
        "Expense": "230,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10012",
        "Age": "22",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "2,000,000",
        "Frequency": "2",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10013",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "80,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10014",
        "Age": "40",
        "Region": "Jeju",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,500,000",
        "Frequency": "8",
        "Expense": "100,000",
        "Date": "2019/05/09",
        "rowStatus": "R"
    },
    {
        "ID": "10015",
        "Age": "35",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,100,000",
        "Frequency": "3",
        "Expense": "350,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10016",
        "Age": "31",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10017",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10018",
        "Age": "33",
        "Region": "Daegu",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10019",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10020",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "3,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10021",
        "Age": "37",
        "Region": "Busan",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10022",
        "Age": "28",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10023",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10024",
        "Age": "20",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,300,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10025",
        "Age": "19",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10026",
        "Age": "32",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "8",
        "Expense": "300,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10027",
        "Age": "34",
        "Region": "Busan",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10028",
        "Age": "41",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "1",
        "Expense": "30,000",
        "Date": "2019/04/18",
        "rowStatus": "R"
    },
    {
        "ID": "10029",
        "Age": "42",
        "Region": "Incheon",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "5",
        "Expense": "120,000",
        "Date": "2019/5/8",
        "rowStatus": "R"
    },
    {
        "ID": "10030",
        "Age": "39",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,800,000",
        "Frequency": "8",
        "Expense": "400,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10001",
        "Age": "23",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/07/19",
        "rowStatus": "R"
    },
    {
        "ID": "10002",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "2,300,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/04/03",
        "rowStatus": "R"
    },
    {
        "ID": "10003",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10004",
        "Age": "19",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "1,900,000",
        "Frequency": "5",
        "Expense": "80,000",
        "Date": "2019/05/10",
        "rowStatus": "R"
    },
    {
        "ID": "10005",
        "Age": "34",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "3,500,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10006",
        "Age": "39",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "8",
        "Expense": "500,000",
        "Date": "2019/05/13",
        "rowStatus": "R"
    },
    {
        "ID": "10007",
        "Age": "29",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/04/30",
        "rowStatus": "R"
    },
    {
        "ID": "10008",
        "Age": "25",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "12",
        "Expense": "2,000,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10009",
        "Age": "32",
        "Region": "Incheon",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,000,000",
        "Frequency": "1",
        "Expense": "100,000",
        "Date": "2019/04/15",
        "rowStatus": "R"
    },
    {
        "ID": "10010",
        "Age": "34",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "2,500,000",
        "Frequency": "1",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10011",
        "Age": "36",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,000,000",
        "Frequency": "5",
        "Expense": "230,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10012",
        "Age": "22",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "2,000,000",
        "Frequency": "2",
        "Expense": "50,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10013",
        "Age": "25",
        "Region": "Busan",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "80,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10014",
        "Age": "40",
        "Region": "Jeju",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,500,000",
        "Frequency": "8",
        "Expense": "100,000",
        "Date": "2019/05/09",
        "rowStatus": "R"
    },
    {
        "ID": "10015",
        "Age": "35",
        "Region": "Seoul",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,100,000",
        "Frequency": "3",
        "Expense": "350,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10016",
        "Age": "31",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,900,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10017",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/01",
        "rowStatus": "R"
    },
    {
        "ID": "10018",
        "Age": "33",
        "Region": "Daegu",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10019",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "2,200,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10020",
        "Age": "30",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Divorced",
        "Income": "3,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10021",
        "Age": "37",
        "Region": "Busan",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "4",
        "Expense": "200,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    },
    {
        "ID": "10022",
        "Age": "28",
        "Region": "Incheon",
        "Hobby": "Movie",
        "Status": "Single",
        "Income": "2,800,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10023",
        "Age": "29",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "6",
        "Expense": "500,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10024",
        "Age": "20",
        "Region": "Daegu",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "2,300,000",
        "Frequency": "5",
        "Expense": "150,000",
        "Date": "2019/05/12",
        "rowStatus": "R"
    },
    {
        "ID": "10025",
        "Age": "19",
        "Region": "Jeju",
        "Hobby": "Movie",
        "Status": "Married",
        "Income": "2,200,000",
        "Frequency": "3",
        "Expense": "100,000",
        "Date": "2019/05/06",
        "rowStatus": "R"
    },
    {
        "ID": "10026",
        "Age": "32",
        "Region": "Jeju",
        "Hobby": "Book",
        "Status": "Single",
        "Income": "3,900,000",
        "Frequency": "8",
        "Expense": "300,000",
        "Date": "2019/05/14",
        "rowStatus": "R"
    },
    {
        "ID": "10027",
        "Age": "34",
        "Region": "Busan",
        "Hobby": "PC Game",
        "Status": "Married",
        "Income": "4,200,000",
        "Frequency": "2",
        "Expense": "100,000",
        "Date": "2019/05/03",
        "rowStatus": "R"
    },
    {
        "ID": "10028",
        "Age": "41",
        "Region": "Seoul",
        "Hobby": "PC Game",
        "Status": "Single",
        "Income": "3,800,000",
        "Frequency": "1",
        "Expense": "30,000",
        "Date": "2019/04/18",
        "rowStatus": "R"
    },
    {
        "ID": "10029",
        "Age": "42",
        "Region": "Incheon",
        "Hobby": "Book",
        "Status": "Married",
        "Income": "3,200,000",
        "Frequency": "5",
        "Expense": "120,000",
        "Date": "2019/05/08",
        "rowStatus": "R"
    },
    {
        "ID": "10030",
        "Age": "39",
        "Region": "Seoul",
        "Hobby": "Book",
        "Status": "Divorced",
        "Income": "3,800,000",
        "Frequency": "8",
        "Expense": "400,000",
        "Date": "2019/05/11",
        "rowStatus": "R"
    }
];
dataList1.setJSON(json);

	};
	
	scwin.onpageunload = function() {
		
	};
	
	getType = function ( info ) {             
            var rowIndex = info.rowIndex;
            var colIndex = info.colIndex;
            var returnInfo;
             
            if (dataList1.getCellData(rowIndex, "Age") < 40 && dataList1.getCellData(rowIndex, "Age") > 29) {
                returnInfo = {
                    id : "dynamic_select_" + rowIndex + "_" + colIndex,
                    inputType : "button",
                    options : {
                        viewType: "icon"
                    }
                };                 
            } else {
                returnInfo = {
                    id : "dynamic_text_" + rowIndex + "_" + colIndex,
                    inputType : "text",
                    options : {
                    }
                };
            }
              
            if(returnInfo) {
                console.log( "[typeGetter] (" + rowIndex + ", " + colIndex + ") : " +returnInfo.inputType);
            }
             
            return returnInfo;
        };
 
 
 	getType1 = function ( info ) {             
            var rowIndex = info.rowIndex;
            var colIndex = info.colIndex;
            var returnInfo;
            
            if (dataList1.getCellData(rowIndex, "Hobby") == "Movie") {
                returnInfo = {
                    id : "dynamic_select_" + rowIndex + "_" + colIndex,
                    inputType : "link",
                    options : {
                        viewType: "icon"
                    }
                };
                 
            } else {
                returnInfo = {
                    id : "dynamic_text_" + rowIndex + "_" + colIndex,
                    inputType : "text",
                    options : {
                    }
                };
            }
              
            if(returnInfo) {
                console.log( "[typeGetter] (" + rowIndex + ", " + colIndex + ") : " +returnInfo.inputType);
            }
             
            return returnInfo;
        };
 
	scwin.gridview1_oncellclick = function(row,col) {
		var value = dataList1.getCellData(row, col);	
		
		if (value == "Movie") {
			window.open("https://www.imdb.com/chart/boxoffice/");
		}
		else {
			alert("The value of the cell is '" + value + "'.");
		}
	};
	
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload','ev:onpageunload':'scwin.onpageunload'},E:[{T:1,N:'w2:textbox',A:{label:'oncellclick',style:'width: 90%;height: 45px;margin: 30px 10px 20px 30px;padding: 10px;padding-right: 10px;line-height:32px;background-color:#C0C0C0;font-size:15px;font-family:monospace;font-style:normal;font-weight:bolder;',id:''}},{T:1,N:'w2:gridView',A:{id:'gridview1',style:'width: 90%;height: 50%;margin-left: 30px;',scrollByColumn:'false',defaultCellHeight:'20',scrollByColumnAdaptive:'false',dataList:'data:dataList1',class:'',autoFit:'allColumn',rowNumVisible:'',rowStatusVisible:'',showSortableUseFilter:'',sortable:'',showSortableImage:'',sortedIconPosition:'',useCtrlOnMultisort:'true',editModeEvent:'ondblclick',keyMoveEditMode:'true',focusFlow:'default',focusMode:'none',selectedRowColor:'#0000FF',visibleRowNum:'',noResultMessageStyle:'width: 90%;height: 50%;margin-left: 30px;',setCellInputTypeCustom:'','ev:oncellclick':'scwin.gridview1_oncellclick'},E:[{T:1,N:'w2:caption',A:{style:'',id:'caption1',value:'this is a grid caption.'}},{T:1,N:'w2:header',A:{style:'',id:'header1'},E:[{T:1,N:'w2:row',A:{style:'height: 25px;',id:'row1'},E:[{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column19',value:'Check',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column17',value:'ID',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column15',value:'Age',blockSelect:'false',displayMode:'label',sortable:'false'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column13',value:'Status',blockSelect:'false',displayMode:'label',sortable:''}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column11',value:'Income',blockSelect:'false',displayMode:'label',sortable:''}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column9',value:'Expense',blockSelect:'false',displayMode:'label',sortable:''}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column7',value:'Hobby',blockSelect:'false',displayMode:'label',sortable:''}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column5',value:'Region',blockSelect:'false',displayMode:'label',sortable:''}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column3',value:'Frequency',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px;',id:'column1',value:'Date',blockSelect:'false',displayMode:'label'}}]}]},{T:1,N:'w2:gBody',A:{style:'',id:'gBody1'},E:[{T:1,N:'w2:row',A:{style:'',id:'row2'},E:[{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'checkbox',style:'height:20px',id:'Check',value:'',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'',style:'height:20px',id:'ID',value:'',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'custom',style:'height:20px',id:'Age',value:'',blockSelect:'false',displayMode:'label',typeGetter:'getType'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'select',style:'height:20px;',id:'Status',value:'',blockSelect:'false',displayMode:'label',allOption:'',chooseOption:'',ref:'',sortLabel:'',viewType:''},E:[{T:1,N:'w2:choices',E:[{T:1,N:'w2:itemset',A:{nodeset:'data:dataList2'},E:[{T:1,N:'w2:label',A:{ref:'label'}},{T:1,N:'w2:value',A:{ref:'value'}}]}]}]},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px',id:'Income',value:'',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px',id:'Expense',value:'',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'custom',style:'height:20px',id:'Hobby',value:'',blockSelect:'false',displayMode:'label',sortable:'true',typeGetter:'getType1'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'',style:'height:20px',id:'Region',value:'',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'text',style:'height:20px',id:'Frequency',value:'',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{removeBorderStyle:'false',width:'70',inputType:'calendar',style:'height:20px',id:'date',value:'',blockSelect:'false',displayMode:'label',typeGetter:'',viewType:'icon'}}]}]}]}]}]}]})