/*amd /tabControl-001/tab_getfileInfo.xml 3587 954622af86c3a593c7019c800688f22501a91e1515d7c0cebdb68b05e2988199 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{baseNode:'list',repeatNode:'map',id:'dlt_list1',saveRemovedData:'true'},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{id:'size',name:'name1',dataType:'text'}},{T:1,N:'w2:column',A:{id:'name',name:'name2',dataType:'text'}},{T:1,N:'w2:column',A:{id:'displaySize',name:'name3',dataType:'text'}}]}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){scwin.onpageload = function(){
		scwin.trigger1_onclick = function(e) {
			//tab1번 객체를 가져온다
			debugger;
			var objTab = tabCon.getWindow(1);
			
			//tab1번의 component에 접근한다
			var obj_multi = objTab.multi.getFileInfos();
			
			var len = obj_multi.length;
			
			dlt_list1.setJSON(obj_multi);
		};
		}
}}}]},{T:1,N:'w2:require',A:{src:'/upload/multiUpload.xml'}}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload'},E:[{T:1,N:'w2:tabControl',A:{useTabKeyOnly:'true',useConfirmMessage:'false',confirmTrueAction:'exist',confirmFalseAction:'new',alwaysDraw:'true',style:'position: relative ;width:100%;',id:'tabCon'},E:[{T:1,N:'w2:tabs',A:{label:'info',disabled:'false',style:'width:70px;height:30px;',id:'tabs1'}},{T:1,N:'w2:tabs',A:{disabled:'false',style:'width:70px;height:30px;',label:'multi',id:'tabs2'}},{T:1,N:'w2:content',A:{alwaysDraw:'true',style:'height:322px;',id:'content1',frameMode:''},E:[{T:1,N:'xf:group',A:{style:'height:23px;padding:10px;',id:''},E:[{T:1,N:'xf:trigger',A:{'ev:onclick':'scwin.trigger1_onclick',style:'position: relative;width: 80px;height: 23px;',id:'trigger1',type:'button'},E:[{T:1,N:'xf:label',E:[{T:4,cdata:'getInfo'}]}]}]},{T:1,N:'xf:group',A:{style:'height:150px;padding:10px;',id:''},E:[{T:1,N:'w2:gridView',A:{scrollByColumnAdaptive:'false',fixedColumnWithHidden:'true',dataList:'dlt_list1',useShiftKey:'true',scrollByColumn:'false',style:'position: relative;width: 500px;height: 150px;',ignoreCellClick:'false',id:'',ignoreToggleOnDisabled:'false'},E:[{T:1,N:'w2:header',A:{style:'',id:'header1'},E:[{T:1,N:'w2:row',A:{style:'',id:'row1'},E:[{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px;',id:'column5',value:'size',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px;',id:'column3',value:'name',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{width:'100',inputType:'text',style:'height:20px;',id:'column1',value:'displaySize',blockSelect:'false',displayMode:'label'}}]}]},{T:1,N:'w2:gBody',A:{style:'',id:'gBody1'},E:[{T:1,N:'w2:row',A:{style:'',id:'row2'},E:[{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px',id:'size',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px',id:'name',blockSelect:'false',displayMode:'label'}},{T:1,N:'w2:column',A:{width:'100',inputType:'text',style:'height:20px',id:'displaySize',blockSelect:'false',displayMode:'label'}}]}]}]}]}]},{T:1,N:'w2:content',A:{alwaysDraw:'true',style:'height:322px;',id:'content2',src:'multi_tab.xml',frameMode:'iframe'}}]}]}]}]})