/*amd /Accordion/unCollapseAll_Accordion.xml 2653 e7e36b08eedef5f6cd686cf2da3d094480006d294d77728b903f28ede4c8b5a5 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'DEFAULT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'}},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
        
	scwin.onpageload = function() {
		
	};
	
	scwin.onpageunload = function() {
		
	};
	
	
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload','ev:onpageunload':'scwin.onpageunload'},E:[{T:1,N:'w2:textbox',A:{id:'',label:'Accordion (unCollapseAll="true")',style:'width: 60%;height: 23px;margin: 50px;margin-top: 10px;background-color:#C0C0C0;font-size:15px;padding: 10px;font-family:monospace;font-style:normal;font-weight:bolder;'}},{T:1,N:'w2:accordion',A:{id:'accordion1',unCollapseAll:'true',collapseAll:'',style:'width: 60%;height: 80%;margin: 50px;',collapsible:'',selectedPanel:'',class:'',titleDivTag:'',panelMoveSpeed:''},E:[{T:1,N:'w2:panels',A:{id:'panels1',style:'',class:''},E:[{T:1,N:'w2:panelTitle',A:{id:'panelTitle1',style:'',class:'',label:'1'}},{T:1,N:'w2:panelContent',A:{id:'panelContent1',style:'height:80%;width: 90%;',class:''},E:[{T:1,N:'w2:textbox',A:{id:'',label:'Panel 1',style:'width: 150px;height: 23px;margin: 50px;background-color:#C0C0C0;font-size:15px;padding: 10px;font-family:monospace;font-style:normal;font-weight:bolder;'}}]}]},{T:1,N:'w2:panels',A:{id:'panels2',style:'',class:''},E:[{T:1,N:'w2:panelTitle',A:{id:'panelTitle2',style:'',class:'',label:'2'}},{T:1,N:'w2:panelContent',A:{id:'panelContent2',style:'height:80%;width: 90%;',class:''},E:[{T:1,N:'w2:textbox',A:{id:'',label:'Panel 2',style:'width: 150px;height: 23px;margin: 50px;background-color:#C0C0C0;font-size:15px;padding: 10px;font-family:monospace;font-style:normal;font-weight:bolder;'}}]}]},{T:1,N:'w2:panels',A:{id:'panels3',style:'width: 100%;',class:''},E:[{T:1,N:'w2:panelTitle',A:{id:'panelTitle3',style:'',class:'',label:'3'}},{T:1,N:'w2:panelContent',A:{id:'panelContent3',style:'height:80%;width: 90%;',class:''},E:[{T:1,N:'xf:select1',A:{appearance:'full',id:'select1',style:'position: absolute ;left:589px;top:91px;width: 54px;height: 25px;',selectedIndex:'-1'}},{T:1,N:'w2:textbox',A:{id:'',label:'Panel 3',style:'width: 150px;height: 23px;margin: 50px;background-color:#C0C0C0;font-size:15px;padding: 10px;font-family:monospace;font-style:normal;font-weight:bolder;'}}]}]}]}]}]}]})