/*amd /gridView-017/gridview_onscrollend.xml 5318 cd0eb721e295cb0ccacff8a80a20945c4b24a6147d32e4504f680cbcf6caedcd */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',E:[{T:1,N:'w2:dataList',A:{baseNode:'list',id:'dataList1',repeatNode:'map',saveRemovedData:'true',style:''},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{id:'no',name:'번호',dataType:'text'}},{T:1,N:'w2:column',A:{dataType:'number',id:'amount',name:'금액'}},{T:1,N:'w2:column',A:{dataType:'text',id:'customer_code',name:'고객코드'}},{T:1,N:'w2:column',A:{dataType:'date',id:'end_date',name:'종료시간'}},{T:1,N:'w2:column',A:{dataType:'date',id:'from_date',name:'시작시간'}},{T:1,N:'w2:column',A:{dataType:'text',id:'model_code',name:'모델코드'}},{T:1,N:'w2:column',A:{dataType:'text',id:'national_code',name:'국가코드'}},{T:1,N:'w2:column',A:{dataType:'text',id:'national_word',name:'국가어'}},{T:1,N:'w2:column',A:{dataType:'text',id:'order_no',name:'정렬번호'}},{T:1,N:'w2:column',A:{dataType:'text',id:'order_type',name:'정렬구분'}}]}]}]},{T:1,N:'xf:submission',A:{id:'submission1',ref:'',target:'data:json,{"id":"dataList1","key":"jsondata", "action":"append"}',action:'./sJsonData.jsp',method:'post',mediatype:'application/json',encoding:'UTF-8',instance:'',replace:'',errorHandler:'',customHandler:'',mode:'asynchronous',processMsg:'','ev:submit':'','ev:submitdone':'scwin.submission1_submitdone','ev:submiterror':''}}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
        
			scwin.onpageload = function() {
				scwin.init();
			};
			
			scwin.onpageunload = function() {
				
			};
			
        	var totalRowCnt = 120;
        	var cnt = "8";

        	scwin.init = function(){
     		    $p.executeSubmission( "submission1",{jsondata : {"start":"0","cnt":cnt}});
        	}

			scwin.gridView1_onscrollend = function() {
				var start = dataList1.getRowCount();
				$p.executeSubmission( "submission1",{jsondata : {"start":String(start),"cnt":cnt}});
			};
	
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload','ev:onpageunload':'scwin.onpageunload'},E:[{T:1,N:'xf:group',A:{id:'',style:'margin-top:20px;height:199px;'},E:[{T:1,N:'w2:textbox',A:{id:'textbox3',dataType:'',style:'',class:'titlebox',label:'GridView onscrollend'}},{T:1,N:'w2:gridView',A:{rowNumHeaderValue:'',autoFit:'',rowStatusWidth:'',visibleRowNum:'',class:'',dataDragDrop:'',columnMove:'',dragStartFunction:'',rowNumWidth:'',rowNumVisible:'true',fixedColumnWithHidden:'true',dragDisplayColumn:'',id:'gridView1',dataList:'dataList1',enterKeyMove:'',focusMode:'',style:'position: relative;width:850px;height:186px;',dragEndFunction:'',useShiftKey:'false',scrollByColumn:'false',oddEvenColorDisplay:'false',rowStatusHeaderValue:'',editModeEvent:'','ev:onscrollend':'scwin.gridView1_onscrollend'},E:[{T:1,N:'w2:header',A:{id:'header1',style:''},E:[{T:1,N:'w2:row',A:{id:'row1',style:''},E:[{T:1,N:'w2:column',A:{id:'column11',blockSelect:'false',style:'height:20px;',width:'100',inputType:'text',value:'시작시간'}},{T:1,N:'w2:column',A:{id:'column13',blockSelect:'false',style:'height:20px;',width:'100',inputType:'text',value:'종료시간'}},{T:1,N:'w2:column',A:{id:'column15',blockSelect:'false',style:'height:20px;',width:'80',inputType:'text',value:'고객코드'}},{T:1,N:'w2:column',A:{id:'column9',blockSelect:'false',style:'height:20px;',width:'90',inputType:'text',value:'모델코드'}},{T:1,N:'w2:column',A:{id:'column1',blockSelect:'false',style:'height:20px;',inputType:'text',width:'110',value:'정렬구분'}},{T:1,N:'w2:column',A:{id:'column17',blockSelect:'false',style:'height:20px;',width:'100',inputType:'text',value:'금액'}},{T:1,N:'w2:column',A:{id:'column7',blockSelect:'false',style:'height:20px;',width:'70',inputType:'text',value:'국가코드'}},{T:1,N:'w2:column',A:{id:'column5',blockSelect:'false',style:'height:20px;',width:'140',inputType:'text',value:'국가어',defaultValue:''}}]}]},{T:1,N:'w2:gBody',A:{id:'gBody1',style:''},E:[{T:1,N:'w2:row',A:{id:'row2',style:''},E:[{T:1,N:'w2:column',A:{id:'from_date',blockSelect:'false',style:'height:20px',width:'100',inputType:'text',displayFormat:'yyyy-MM-dd',displayFormatter:''}},{T:1,N:'w2:column',A:{id:'end_date',blockSelect:'false',style:'height:20px',width:'100',inputType:'text',displayFormat:'yyyy-MM-dd',displayFormatter:''}},{T:1,N:'w2:column',A:{id:'customer_code',blockSelect:'false',style:'height:20px',width:'80',inputType:'text'}},{T:1,N:'w2:column',A:{id:'model_code',blockSelect:'false',style:'height:20px',width:'90',inputType:'text'}},{T:1,N:'w2:column',A:{id:'order_type',blockSelect:'false',style:'height:20px',inputType:'text',width:'110'}},{T:1,N:'w2:column',A:{id:'amount',blockSelect:'false',style:'height:20px',width:'100',inputType:'text',displayFormat:'###,###'}},{T:1,N:'w2:column',A:{id:'national_code',blockSelect:'false',style:'height:20px',width:'70',inputType:'text'}},{T:1,N:'w2:column',A:{id:'national_word',blockSelect:'false',style:'height:20px',width:'70',inputType:'text'}}]}]}]}]}]}]}]})