/*amd /GridView/_General/contextMenu_GridView.xml 4552 7c806602411d62b57e7404f9b62d674158bec7d8a7e5bcbf12d4d2eeeb0ed949 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',A:{},E:[{T:1,N:'w2:type',E:[{T:3,text:'DEFAULT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{baseNode:'list',id:'dataList1',repeatNode:'map',saveRemovedData:'true',style:''},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{dataType:'text',id:'col1',name:'Continent'}},{T:1,N:'w2:column',A:{dataType:'text',id:'col2',name:'Country'}},{T:1,N:'w2:column',A:{dataType:'text',id:'col3',name:'Item'}},{T:1,N:'w2:column',A:{dataType:'text',id:'col4',name:'Quantity'}}]},{T:1,N:'w2:data',A:{use:'true'},E:[{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'Asia'}]},{T:1,N:'col2',E:[{T:4,cdata:'Korea'}]},{T:1,N:'col3',E:[{T:4,cdata:'Freezer'}]},{T:1,N:'col4',E:[{T:4,cdata:'300'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'Asia'}]},{T:1,N:'col2',E:[{T:4,cdata:'China'}]},{T:1,N:'col3',E:[{T:4,cdata:'Washer'}]},{T:1,N:'col4',E:[{T:4,cdata:'700'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'Europe'}]},{T:1,N:'col2',E:[{T:4,cdata:'Germany'}]},{T:1,N:'col3',E:[{T:4,cdata:'TV'}]},{T:1,N:'col4',E:[{T:4,cdata:'350'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'Europe'}]},{T:1,N:'col2',E:[{T:4,cdata:'France'}]},{T:1,N:'col3',E:[{T:4,cdata:'Washer'}]},{T:1,N:'col4',E:[{T:4,cdata:'400'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'Americas'}]},{T:1,N:'col2',E:[{T:4,cdata:'Canada'}]},{T:1,N:'col3',E:[{T:4,cdata:'TV'}]},{T:1,N:'col4',E:[{T:4,cdata:'330'}]}]},{T:1,N:'w2:row',E:[{T:1,N:'col1',E:[{T:4,cdata:'Americas'}]},{T:1,N:'col2',E:[{T:4,cdata:'Mexico'}]},{T:1,N:'col3',E:[{T:4,cdata:'Freezer'}]},{T:1,N:'col4',E:[{T:4,cdata:'500'}]}]}]}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'script',A:{type:'text/javascript',lazy:'false'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
        
	scwin.onpageload = function() {
		
	};
	
	scwin.onpageunload = function() {		
			
	};
	
	
	
	
	
	
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload','ev:onpageunload':'scwin.onpageunload'},E:[{T:1,N:'w2:gridView',A:{id:'gridView1',style:'width: 250px;height: 100px;margin: 30px;margin-top: 50px;margin-left: 100px;',checkAllType:'false',scrollByColumn:'false',defaultCellHeight:'20',scrollByColumnAdaptive:'false',dataList:'data:dataList1',autoFit:'',visibleRowNum:'13',rowNumVisible:'',sortable:'',showSortableUseFilter:'',useFilterList:'true',noResultMessageVisible:'',copyOption:'',copyType:'native',useCtrlKey:'',focusMode:'cell',useShiftKey:'true',selectedCellColor:'#FF8040',showSortableImage:'',noResultMessage:'No data.',noResultMessageClass:'',noResultMessageVisibleAlways:'true',contextMenu:'true',contextMenuAltClick:''},E:[{T:1,N:'w2:caption',A:{style:'',id:'caption1',value:'this is a grid caption.'}},{T:1,N:'w2:header',A:{style:'',id:'header1'},E:[{T:1,N:'w2:row',A:{style:'',id:'row1'},E:[{T:1,N:'w2:column',A:{width:'70',inputType:'',style:'height:20px',id:'column4',value:'Continent',displayMode:'label'}},{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px',id:'column3',value:'Country',displayMode:'label'}},{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px',id:'column2',value:'Item',displayMode:'label',useFilter:'',sortLabel:''}},{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px',id:'column1',value:'Quantity',displayMode:'label'}}]}]},{T:1,N:'w2:gBody',A:{style:'',id:'gBody1'},E:[{T:1,N:'w2:row',A:{style:'',id:'row2'},E:[{T:1,N:'w2:column',A:{width:'70',inputType:'',style:'height:20px',id:'col1',value:'',displayMode:'label',embeddedInput:'',allOption:'',chooseOption:'',ref:''},E:[{T:1,N:'w2:choices',E:[{T:1,N:'w2:itemset',A:{nodeset:'data:dataList2'},E:[{T:1,N:'w2:label',A:{ref:'label'}},{T:1,N:'w2:value',A:{ref:'value'}}]}]}]},{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px',id:'col2',value:'',displayMode:'label'}},{T:1,N:'w2:column',A:{width:'70',inputType:'',style:'height:20px',id:'col3',value:'',displayMode:'label',validateOnInput:'',allOption:'',chooseOption:'',ref:''},E:[{T:1,N:'w2:choices',E:[{T:1,N:'w2:itemset',A:{nodeset:'data:dataList3'},E:[{T:1,N:'w2:label',A:{ref:'label'}},{T:1,N:'w2:value',A:{ref:'value'}}]}]}]},{T:1,N:'w2:column',A:{width:'70',inputType:'text',style:'height:20px',id:'col4',value:'',displayMode:'label',dataType:''}}]}]}]}]}]}]})